apiVersion: v1
kind: Service
metadata:
  name: __SERVICE__
  namespace: default

## If this service needs to be publically accessible, uncomment the following
## annotations - k8s will create an AWS ELB for you for the specified hostname.
#
#  annotations:
#    external-dns.alpha.kubernetes.io/hostname: __SERVICE__.superpower-staging.com
#    service.beta.kubernetes.io/aws-load-balancer-ssl-cert: arn:aws:acm:us-east-1:554179259394:certificate/dc505934-95e6-49a0-b9fd-df2092b3c050
#    service.beta.kubernetes.io/aws-load-balancer-ssl-ports: "https"
#    service.beta.kubernetes.io/aws-load-balancer-backend-protocol: "http"

spec:
  selector:
    app: __SERVICE__
  ports:
  - name: https
    port: 443
    targetPort: 8080
  type: LoadBalance
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: __SERVICE__
  namespace: default
  labels:
    app: __SERVICE__
spec:
  replicas: 2
  selector:
    matchLabels:
      app: __SERVICE__
  template:
    metadata:
      labels:
        app: __SERVICE__
    spec:
      containers:
      - name: __SERVICE__
        image: __AWS_ECR_URL__/__SERVICE__:__VERSION__
        ports:
        - containerPort: 8080
        resources:
          requests:
            memory: "256Mi"
            cpu: "256m"
          limits:
            memory: "512Mi"
            cpu: "512m"
        livenessProbe:
          httpGet:
            path: /health-check
            port: 8080
          initialDelaySeconds: 30
          periodSeconds: 5
        env:
        # Name of the service (used in health-check, version)
        - name: GO_SVC_TEMPLATE_SERVICE_NAME
          value: "go-svc-template"

        # HTTP port the service will bind its API server to
        - name: GO_SVC_TEMPLATE_API_LISTEN_ADDRESS
          value: ":8080"

        # Service uses 'uber/zap' for logging; it has two available log "modes":
        # 'dev' and 'prod'. 'dev' causes logs to be colorized and human-readable;
        # 'prod' will log in JSON format w/o colors.
        - name: GO_SVC_TEMPLATE_LOG_CONFIG
          value: "dev"

        # Whether to enable pprof endpoints
        - name: GO_SVC_TEMPLATE_ENABLE_PPROF
          value: "true"

        # New Relic license key; remove if not using New Relic
        - name: GO_SVC_TEMPLATE_NEW_RELIC_LICENSE_KEY
          value: "{{ .GO_SVC_TEMPLATE_NEW_RELIC_LICENSE_KEY }}"

        # If using NR, how the service will be identified in NR UI
        - name: GO_SVC_TEMPLATE_NEW_RELIC_APP_NAME
          value: "go-svc-template (STG)"

        ################ RabbitMQ Consumer / Processor Config #################

        # RabbitMQ URL (expects full DSN)
        - name: GO_SVC_TEMPLATE_PROCESSOR_RABBIT_URL
          value: "{{ .GO_SVC_TEMPLATE_PROCESSOR_RABBIT_URL }}"

        # Routing key used for publishing messages
        #
        # NOTE: Only applicable when 'rabbit' lib is in 'publisher' or 'both' mode.
        - name: GO_SVC_TEMPLATE_PROCESSOR_RABBIT_ROUTING_KEY
          value: "routing-key-used-by-publisher"

        # Name of the exchange queue will be bound to.
        #
        # NOTE: Only applicable when 'rabbit' lib is in 'consumer' or 'both' mode.
        - name: GO_SVC_TEMPLATE_PROCESSOR_RABBIT_EXCHANGE_NAME
          value: "events"

        # Whether the service should create the exchange if it doesn't exist.
        #
        # NOTE: Only applicable when 'rabbit' lib is in 'consumer' or 'both' mode.
        - name: GO_SVC_TEMPLATE_PROCESSOR_RABBIT_EXCHANGE_DECLARE
          value: "true"

        # When true, the exchange will be created with durable flag so it will
        # be able to survive a broker restart.
        #
        # NOTE: Only applicable when 'rabbit' lib is in 'consumer' or 'both' mode.
        - name: GO_SVC_TEMPLATE_PROCESSOR_RABBIT_EXCHANGE_DURABLE
          value: "true"

        # What routing key consumers will bind to. NOTE: Use '#' for wildcards.
        #
        # Example 1: "events.webhooks.wearable" will cause rabbitmq to forward
        # only wearable webhook events to 'GO_SVC_TEMPLATE_PROCESSOR_RABBIT_QUEUE_NAME'.
        #
        # Example 2: "events.webhooks.#" will cause rabbitmq to forward all
        # webhook events to 'GO_SVC_TEMPLATE_PROCESSOR_RABBIT_QUEUE_NAME'.
        #
        # Example 3: "events.#.wearable" will cause rabbitmq to forward ALL
        # wearable events to 'GO_SVC_TEMPLATE_PROCESSOR_RABBIT_QUEUE_NAME'.
        #
        # NOTE: Only applicable when 'rabbit' lib is in 'consumer' or 'both' mode.
        - name: GO_SVC_TEMPLATE_PROCESSOR_RABBIT_BINDING_KEYS
          value: "routing-key-to-bind-to"

        # When left empty, rabbitmq will generate a random queue name. This
        # effectively means that all consumers will receive a COPY of the
        # message when binding to same routing key. This is a good pattern for
        # implementing broadcast/fanout-like behavior.
        #
        # NOTE: Only applicable when 'rabbit' lib is in 'consumer' or 'both' mode.
        - name: GO_SVC_TEMPLATE_PROCESSOR_RABBIT_QUEUE_NAME
          value: "go-svc-template"

        # Whether the service should create the queue if it doesn't exist
        #
        # NOTE: Only applicable when 'rabbit' lib is in 'consumer' or 'both' mode.
        - name: GO_SVC_TEMPLATE_PROCESSOR_RABBIT_QUEUE_DECLARE
          value: "true"

        # When true, the queue will be created with durable flag so it will
        # be able to survive a broker restart.
        #
        # NOTE: Only applicable when 'rabbit' lib is in 'consumer' or 'both' mode.
        - name: GO_SVC_TEMPLATE_PROCESSOR_RABBIT_QUEUE_DURABLE
          value: "true"

        # When true, rabbitmq will delete the queue when the queue no longer
        # has any consumers. You probably don't want this.
        #
        # NOTE: Only applicable when 'rabbit' lib is in 'consumer' or 'both' mode.
        - name: GO_SVC_TEMPLATE_PROCESSOR_RABBIT_QUEUE_AUTO_DELETE
          value: "false"

        # When true, the queue can only be accessed by exactly one consumer.
        # You probably don't want this.
        #
        # NOTE: Only applicable when 'rabbit' lib is in 'consumer' or 'both' mode.
        - name: GO_SVC_TEMPLATE_PROCESSOR_RABBIT_QUEUE_EXCLUSIVE
          value: "false"

        # Determines the size of the consumer worker pool
        - name: GO_SVC_TEMPLATE_PROCESSOR_RABBIT_NUM_CONSUMERS
          value: "4"

        ################ RabbitMQ Producer / Publisher Config #################

        - name: GO_SVC_TEMPLATE_PUBLISHER_RABBIT_URL
          value: {{ .GO_SVC_TEMPLATE_PUBLISHER_RABBIT_URL }}

        - name: GO_SVC_TEMPLATE_PUBLISHER_RABBIT_EXCHANGE_NAME
          value: "events"

        - name: GO_SVC_TEMPLATE_PUBLISHER_RABBIT_EXCHANGE_DECLARE
          value: "true"

        - name: GO_SVC_TEMPLATE_PUBLISHER_RABBIT_EXCHANGE_DURABLE
          value: "true"
