apiVersion: v1
kind: Service
metadata:
  name: {{SERVICE}}
  namespace: default
spec:
  selector:
    app: {{SERVICE}}
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{SERVICE}}
  namespace: default
  labels:
    app: {{SERVICE}}
spec:
  replicas: 2
  selector:
    matchLabels:
      app: {{SERVICE}}
  template:
    metadata:
      labels:
        app: {{SERVICE}}
    spec:
      containers:
      - name: {{SERVICE}}
        image: {{AWS_ECR_URL}}/{{SERVICE}}:{{VERSION}}
        ports:
        - containerPort: 8080
        resources:
          requests:
            memory: "256Mi"
            cpu: "256m"
          limits:
            memory: "512Mi"
            cpu: "512m"
        livenessProbe:
          httpGet:
            path: /health-check
            port: 8080
          initialDelaySeconds: 30
          periodSeconds: 5
        env:
        - name: GO_SVC_TEMPLATE_SERVICE_NAME
          value: "go-svc-template"
        - name: GO_SVC_TEMPLATE_API_LISTEN_ADDRESS
          value: ":8080"
        - name: GO_SVC_TEMPLATE_LOG_CONFIG
          value: "dev"
        - name: GO_SVC_TEMPLATE_ENABLE_PPROF
          value: "true"
        - name: GO_SVC_TEMPLATE_NEW_RELIC_APP_NAME
          value: "go-svc-template (STAGE)"
        - name: GO_SVC_TEMPLATE_NEW_RELIC_LICENSE_KEY
          value: "{{ .NEW_RELIC_LICENSE_KEY }}"
        - name: GO_SVC_TEMPLATE_RABBIT_URL
          value: "{{ .RABBIT_URL }}"
        - name: GO_SVC_TEMPLATE_RABBIT_ROUTING_KEY
          value: "routing-key"
        - name: GO_SVC_TEMPLATE_RABBIT_EXCHANGE_NAME
          value: "events"
        - name: GO_SVC_TEMPLATE_RABBIT_EXCHANGE_DECLARE
          value: "true"
        - name: GO_SVC_TEMPLATE_RABBIT_EXCHANGE_DURABLE
          value: "true"
        - name: GO_SVC_TEMPLATE_RABBIT_BINDING_KEYS
          value: "routing-key"
        - name: GO_SVC_TEMPLATE_RABBIT_QUEUE_NAME
          value: "go-svc-template"
        - name: GO_SVC_TEMPLATE_RABBIT_QUEUE_DECLARE
          value: "true"
        - name: GO_SVC_TEMPLATE_RABBIT_QUEUE_DURABLE
          value: "true"
        - name: GO_SVC_TEMPLATE_RABBIT_QUEUE_AUTO_DELETE
          value: "false"
        - name: GO_SVC_TEMPLATE_RABBIT_QUEUE_EXCLUSIVE
          value: "false"
        - name: GO_SVC_TEMPLATE_RABBIT_NUM_CONSUMERS
          value: "4"
