// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.15.0

package gensql

import (
	"database/sql"
	"encoding/json"
	"time"

	"github.com/google/uuid"
)

type Genre struct {
	ID   uuid.UUID
	Name string
	Slug string
}

type Release struct {
	ID            uuid.UUID
	Title         string
	Artist        string
	AlbumArtUrl   string
	ReleaseDate   time.Time
	Label         string
	LabelUrl      sql.NullString
	FollowerCount int32
	Genres        json.RawMessage
	Country       sql.NullString
	ExternalLinks json.RawMessage
	SpotifyUrl    sql.NullString
	YoutubeUrl    sql.NullString
	BandcampUrl   sql.NullString
	CreatedAt     time.Time
	UpdatedAt     time.Time
}
