INSERT INTO genres (id, name, slug) VALUES
(gen_random_uuid(), 'Death Metal', 'death-metal'),
(gen_random_uuid(), 'Black Metal', 'black-metal'),
(gen_random_uuid(), 'Thrash Metal', 'thrash-metal'),
(gen_random_uuid(), 'Doom Metal', 'doom-metal'),
(gen_random_uuid(), 'Heavy Metal', 'heavy-metal'),
(gen_random_uuid(), 'Melodic Death Metal', 'melodic-death-metal'),
(gen_random_uuid(), 'Technical Death Metal', 'technical-death-metal'),
(gen_random_uuid(), 'Progressive Metal', 'progressive-metal'),
(gen_random_uuid(), 'Power Metal', 'power-metal'),
(gen_random_uuid(), 'Symphonic Metal', 'symphonic-metal'),
(gen_random_uuid(), 'Folk Metal', 'folk-metal'),
(gen_random_uuid(), 'Viking Metal', 'viking-metal'),
(gen_random_uuid(), 'Melodic Black Metal', 'melodic-black-metal'),
(gen_random_uuid(), 'Atmospheric Black Metal', 'atmospheric-black-metal'),
(gen_random_uuid(), 'Post-Black Metal', 'post-black-metal'),
(gen_random_uuid(), 'Sludge Metal', 'sludge-metal'),
(gen_random_uuid(), 'Stoner Metal', 'stoner-metal'),
(gen_random_uuid(), 'Funeral Doom Metal', 'funeral-doom-metal'),
(gen_random_uuid(), 'Death Doom Metal', 'death-doom-metal'),
(gen_random_uuid(), 'Grindcore', 'grindcore'),
(gen_random_uuid(), 'Goregrind', 'goregrind'),
(gen_random_uuid(), 'Deathcore', 'deathcore'),
(gen_random_uuid(), 'Metalcore', 'metalcore'),
(gen_random_uuid(), 'Hardcore', 'hardcore'),
(gen_random_uuid(), 'Post-Hardcore', 'post-hardcore'),
(gen_random_uuid(), 'Nu Metal', 'nu-metal'),
(gen_random_uuid(), 'Industrial Metal', 'industrial-metal'),
(gen_random_uuid(), 'Alternative Metal', 'alternative-metal'),
(gen_random_uuid(), 'Groove Metal', 'groove-metal'),
(gen_random_uuid(), 'Speed Metal', 'speed-metal'),
(gen_random_uuid(), 'Traditional Heavy Metal', 'traditional-heavy-metal'),
(gen_random_uuid(), 'Epic Heavy Metal', 'epic-heavy-metal'),
(gen_random_uuid(), 'New Wave of British Heavy Metal', 'nwobhm'),
(gen_random_uuid(), 'Neoclassical Metal', 'neoclassical-metal'),
(gen_random_uuid(), 'Symphonic Power Metal', 'symphonic-power-metal'),
(gen_random_uuid(), 'Folk Power Metal', 'folk-power-metal'),
(gen_random_uuid(), 'Celtic Metal', 'celtic-metal'),
(gen_random_uuid(), 'Pagan Metal', 'pagan-metal'),
(gen_random_uuid(), 'Industrial Black Metal', 'industrial-black-metal'),
(gen_random_uuid(), 'Blackened Death Metal', 'blackened-death-metal'),
(gen_random_uuid(), 'Melodic Blackened Death Metal', 'melodic-blackened-death-metal'),
(gen_random_uuid(), 'Brutal Death Metal', 'brutal-death-metal'),
(gen_random_uuid(), 'Slam Death Metal', 'slam-death-metal'),
(gen_random_uuid(), 'Progressive Death Metal', 'progressive-death-metal'),
(gen_random_uuid(), 'Atmospheric Death Metal', 'atmospheric-death-metal'),
(gen_random_uuid(), 'Death ''n'' Roll', 'death-n-roll'),
(gen_random_uuid(), 'Black ''n'' Roll', 'black-n-roll'),
(gen_random_uuid(), 'Crust Punk', 'crust-punk'),
(gen_random_uuid(), 'Crossover Thrash', 'crossover-thrash'),
(gen_random_uuid(), 'Thrashcore', 'thrashcore'),
(gen_random_uuid(), 'D-Beat', 'd-beat'),
(gen_random_uuid(), 'Hardcore Punk', 'hardcore-punk'),
(gen_random_uuid(), 'Gothic Metal', 'gothic-metal'),
(gen_random_uuid(), 'Symphonic Gothic Metal', 'symphonic-gothic-metal'),
(gen_random_uuid(), 'Avant-Garde Metal', 'avant-garde-metal'),
(gen_random_uuid(), 'Experimental Metal', 'experimental-metal'),
(gen_random_uuid(), 'Mathcore', 'mathcore'),
(gen_random_uuid(), 'Djent', 'djent'),
(gen_random_uuid(), 'Progressive Metalcore', 'progressive-metalcore'),
(gen_random_uuid(), 'Djentcore', 'djentcore'),
(gen_random_uuid(), 'Ambient Black Metal', 'ambient-black-metal'),
(gen_random_uuid(), 'Depressive Black Metal', 'depressive-black-metal'),
(gen_random_uuid(), 'Raw Black Metal', 'raw-black-metal'),
(gen_random_uuid(), 'War Metal', 'war-metal'),
(gen_random_uuid(), 'Bestial Black Metal', 'bestial-black-metal'),
(gen_random_uuid(), 'Black ''n'' Death', 'black-n-death'),
(gen_random_uuid(), 'Post-Metal', 'post-metal'),
(gen_random_uuid(), 'Drone Metal', 'drone-metal'),
(gen_random_uuid(), 'Symphonic Black Metal', 'symphonic-black-metal'),
(gen_random_uuid(), 'Folk Black Metal', 'folk-black-metal'),
(gen_random_uuid(), 'Pagan Black Metal', 'pagan-black-metal'),
(gen_random_uuid(), 'Viking Black Metal', 'viking-black-metal'),
(gen_random_uuid(), 'Celtic Black Metal', 'celtic-black-metal'),
(gen_random_uuid(), 'Technical Thrash Metal', 'technical-thrash-metal'),
(gen_random_uuid(), 'Progressive Thrash Metal', 'progressive-thrash-metal'),
(gen_random_uuid(), 'Melodic Thrash Metal', 'melodic-thrash-metal'),
(gen_random_uuid(), 'Black Thrash', 'black-thrash'),
(gen_random_uuid(), 'Death Thrash', 'death-thrash'),
(gen_random_uuid(), 'US Power Metal', 'us-power-metal'),
(gen_random_uuid(), 'European Power Metal', 'european-power-metal'),
(gen_random_uuid(), 'Progressive Power Metal', 'progressive-power-metal'),
(gen_random_uuid(), 'Neoclassical Power Metal', 'neoclassical-power-metal'),
(gen_random_uuid(), 'Epic Power Metal', 'epic-power-metal'),
(gen_random_uuid(), 'Melodic Power Metal', 'melodic-power-metal'),
(gen_random_uuid(), 'Opera Metal', 'opera-metal')
ON CONFLICT (name) DO NOTHING;


